### ISSUE TITLE
空库启动服务提示报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-contracts-app#26]
(node:102300) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:102300) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
WARNING: npm peer requirements (for steedos:cfs-data-man) not installed:
 - mime@1.6.0 installed, mime@^2.0.2 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

(node:102300) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.
WARNING: not found plugin.config.yml E:\github\steedos-contracts-app\node_modules\@steedos\accounts\plugin.config.yml

You are using the default secret "secret" which is not secure.
Please change it with a strong random token.
MongoError: Index with name: c2_is_deleted already exists with a different name
    at Connection.<anonymous> (E:\github\steedos-contracts-app\node_modules\mongodb\lib\core\connection\pool.js:466:61)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at processMessage (E:\github\steedos-contracts-app\node_modules\mongodb\lib\core\connection\connection.js:364:10)
    at Socket.<anonymous> (E:\github\steedos-contracts-app\node_modules\mongodb\lib\core\connection\connection.js:533:15)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by hotlong** [comment]
目前只能使用 MongoDB Community Server v3.6 版本，https://developer.steedos.com/docs/developer/guide
